### ISSUE TITLE
Option to bypass WP core and/or symlinked files

### ISSUE THREAD

**Issue by Spl0itable** [wordfence/wordfence-cli#108]
Hello,

We symlink all core files within /wordpress among others and would rather bypass those files. I've looked at the available options, but doesn't seem possible to bypass core/symlinked files. Is it possible to add a new flag to bypass checking for core files, etc? Example error:

```
Scanning site at /www...
Traceback (most recent call last):
  File "/www/wordfence-cli/wordfence/wordpress/site.py", line 58, in _is_core_directory
    if file.is_file():
PermissionError: [Errno 13] Permission denied: '/www/wp-load.php'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wordfence-cli/main.py", line 4, in <module>
    cli.main()
  File "/www/wordfence-cli/wordfence/cli/cli.py", line 181, in main
    exit_code = cli.invoke()
  File "/www/wordfence-cli/wordfence/cli/cli.py", line 175, in invoke
    return self.process_exception(exception)
  File "/www/wordfence-cli/wordfence/cli/cli.py", line 102, in process_exception
    raise exception
  File "/www/wordfence-cli/wordfence/cli/cli.py", line 171, in invoke
    return self.subcommand.invoke()
  File "/www/wordfence-cli/wordfence/cli/vulnscan/vulnscan.py", line 216, in invoke
    self._scan_site(
  File "/www/wordfence-cli/wordfence/cli/vulnscan/vulnscan.py", line 153, in _scan_site
    self._scan(
  File "/www/wordfence-cli/wordfence/cli/vulnscan/vulnscan.py", line 77, in _scan
    site = WordpressSite(
  File "/www/wordfence-cli/wordfence/wordpress/site.py", line 49, in __init__
    self.core_path = self._locate_core()
  File "/www/wordfence-cli/wordfence/wordpress/site.py", line 111, in _locate_core
    if self._is_core_directory(self.path):
  File "/www/wordfence-cli/wordfence/wordpress/site.py", line 68, in _is_core_directory
    raise WordpressException(
wordfence.wordpress.exceptions.WordpressException: Unable to scan directory at /www
```

Thanks

**Comment by akenion** [comment]
Some interaction with WordPress core is necessary to determine the location of plugin and theme directories as they can be moved to non-standard paths in various ways.

That said, Wordfence CLI does support scanning only plugins and themes using the `--plugin-directory/-p` and `--theme-directory/-t` arguments rather than specifying paths to the WordPress core files.

```
wordfence vuln-scan -p /var/www/html/wp-content/plugins -t /var/www/html/wp-content/themes
```

If you need to scan `mu-plugins` as well, you can add that as a plugin directory as well (i.e. `-p /var/www/html/wp-content/mu-plugins`).
