### ISSUE TITLE
Gracefully handle errors reading stdin (or writing stdout) when prompting for configuration

### ISSUE THREAD

**Issue by akenion** [wordfence/wordfence-cli#128]
If CLI is run in a way that necessitates prompting for configuration, it fails with a generic IO error if it cannot prompt the user.

It should fail gracefully and instruct the user to either use the non-interactive configuration option (#107) or ensure an existing config file has been set up prior to running the command.

```
Wordfence CLI cannot be used until it has been configured. Would you like to configure it now? [y/n] (default: n): Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/alex/Defiant/wordfence-cli/wordfence/cli/cli.py", line 188, in <module>
    main()
  File "/home/alex/Defiant/wordfence-cli/wordfence/cli/cli.py", line 181, in main
    exit_code = cli.invoke()
  File "/home/alex/Defiant/wordfence-cli/wordfence/cli/cli.py", line 163, in invoke
    and not configurer.check_config():
  File "/home/alex/Defiant/wordfence-cli/wordfence/cli/configurer.py", line 382, in check_config
    self.prompt_for_missing_config()
  File "/home/alex/Defiant/wordfence-cli/wordfence/cli/configurer.py", line 366, in prompt_for_missing_config
    should_configure = prompt_yes_no(
  File "/home/alex/Defiant/wordfence-cli/wordfence/util/input.py", line 59, in prompt_yes_no
    return prompt(
  File "/home/alex/Defiant/wordfence-cli/wordfence/util/input.py", line 20, in prompt
    response = input(f'{message}{default_message}: ')
EOFError: EOF when reading a line
```

**Comment by davidnuzik** [comment]
`30e3249` (after rc2, before rc3) 11/27/23 built with pip

**SUMMARY:**
QA validation PASSED.

**VALIDATION STEPS**
1. Try to run wordfence in a non-interactive way without any config done prior, or by other means such as just trying to pass input into wordfence configure.
2. The result is this is now handled nicely and a message is output: `Wordfence CLI does not appear to be running interactively and cannot prompt for configuration. Please run Wordfence CLI in a terminal, specify the configuration options using the various command line parameters, or set up a configuration file manually. Run wordfence configure --help for additional information.`

**NOTES:**
I tested in various ways including with my automation I am building out and can confirm with pretty high confidence that this works as expected. When testing manually you can (for example) run `echo -e "n\n" | ./wordfence configure` in order to trigger this message or by other means such as trying to input to wordfence on an unconfigured machine.
