### ISSUE TITLE
Using the -l/--license option is throwing an InvalidCachedValueException error 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#171]
When using a new license key with the -l/--license option, CLI is failing to retrieve a new value for the license and instead attempting to use the cached value. This in turn triggers an error when an InvalidCachedValueException is thrown. 

An example to reproduce: 

1. Run `wordfence malware-scan .` using the license defined in the wordfence-cli.ini file. 
2. Next attempt `wordfence malware-scan . -l <license-key> `

Designating --no-cache overrides the error and allows the defined license key to validate. 

Traceback details: 

> File "/Library/Frameworks/Python.framework/Versions/3.11/bin/wordfence", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 167, in main
    return cli.process_exception(exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 76, in process_exception
    raise exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 165, in main
    return cli.invoke()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 146, in invoke
    terms_manager.prompt_acceptance_if_needed()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/terms_management.py", line 32, in prompt_acceptance_if_needed
    acceptance = self.context.cache.get(ACCEPTANCE_CACHE_KEY)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/caching.py", line 49, in get
    return self.filter_value(
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/caching.py", line 64, in filter_value
    value = filter(value)
            ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/context.py", line 117, in filter_cache_entry
    raise InvalidCachedValueException(
wordfence.util.caching.InvalidCachedValueException: Incompatible license

**Comment by ewodrich** [comment]
Additional note from further testing: 
Using -c or -l with --accept-terms and then attempting a different -c or -l license key is producing the same "terms" error as above, even when designating --no-cache. 

When retesting be sure to include testing --accept-terms on a license and then testing a new license or config file with a different license after using --accept-terms on the initial test.

**Comment by ewodrich** [comment]
Re-opening for continued error message when first attempting -l option with a new license (Mac & Linux). Also recreated by running `--purge-cache` and then performing `wordfence malware-scan .` Rerunning the same command a second time resolves the issue. 

> Traceback (most recent call last):
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/terms_management.py", line 32, in prompt_acceptance_if_needed
    acceptance = self.context.cache.get(ACCEPTANCE_CACHE_KEY)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/util/caching.py", line 49, in get
    return self.filter_value(
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/util/caching.py", line 64, in filter_value
    value = filter(value)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/context.py", line 117, in filter_cache_entry
    raise InvalidCachedValueException(
wordfence.util.caching.InvalidCachedValueException: Incompatible license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/esther/.local/bin/wordfence", line 8, in <module>
    sys.exit(main())
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/cli.py", line 173, in main
    return exception_handler.process_exception(exception)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/cli.py", line 43, in process_exception
    raise exception
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/cli.py", line 171, in main
    return cli.invoke()
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/cli.py", line 158, in invoke
    terms_manager.prompt_acceptance_if_needed()
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/terms_management.py", line 41, in prompt_acceptance_if_needed
    client.ping_api_key()
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/api/noc1.py", line 134, in ping_api_key
    return self.process_simple_request('ping_api_key')
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/api/noc1.py", line 79, in process_simple_request
    self.validate_response(response, validator)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/api/noc1.py", line 71, in validate_response
    self._trigger_terms_update_hooks(terms_updated, self.license)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/api/noc1.py", line 43, in _trigger_terms_update_hooks
    hook(updated, license)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/terms_management.py", line 78, in trigger_update
    self.prompt_acceptance(license.paid)
  File "/home/esther/.local/lib/python3.10/site-packages/wordfence/cli/terms_management.py", line 84, in prompt_acceptance
    if license.paid:
AttributeError: 'bool' object has no attribute 'paid'

**Comment by ewodrich** [comment]
Verified this is working as intended and without error while using a variety of licenses settings with both malware-scan and vuln-scan. This includes: 

- purge-cache
- no-cache
- -c option
- -l brand new license
- -l existing licenses
- attempting exact prior scenarios that previously created errors
