### ISSUE TITLE
Mac specific: Errors occurring from how Mac is using our cache data. 

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#182]
Error on Mac testing with using the -c option related to how Mac is using the cache data. 
Ex: `wordfence vuln-scan . -c /Users/Esthe/.config/wordfence/wordfence-prem.ini `
`Error: Global _sitebuiltins._Printer is not allowed`

Running `wordfence vuln-scan . `fails with the same error once it's been triggered. 

Resolved the issue by running `wordfence vuln-scan . --purge-cache` and then ran `wordfence vuln-scan .` twice after without problems. 

Full error message: 

> Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.11/bin/wordfence", line 8, in <module>
  sys.exit(main())
       ^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 173, in main
  return exception_handler.process_exception(exception)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 43, in process_exception
  raise exception
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 171, in main
  return cli.invoke()
      ^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 157, in invoke
  license_manager.check_license()
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/licensing.py", line 61, in check_license
  cached = self.context.cache.get(CACHE_KEY)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/caching.py", line 50, in get
  self._deserialize_value(self._load(key, max_age))
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/caching.py", line 113, in _deserialize_value
  return limited_deserialize(value, self.allowed)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/serialization.py", line 30, in limited_deserialize
  return LimitedDeserializer(data, allowed).load()
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/util/serialization.py", line 21, in find_class
  raise ProhibitedTypeException(f'Global {full_name} is not allowed')
wordfence.util.serialization.ProhibitedTypeException: Global _sitebuiltins._Printer is not allowed

**Comment by akenion** [comment]
This was introduced by the changes for #107 and has since been corrected in the scope of that case based on @davidnuzik's report here:
https://github.com/wordfence/wordfence-cli/issues/107#issuecomment-1836373230
