### ISSUE TITLE
Mac: Error when using -x and -n options to include or exclude file(s)

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#191]
Command: `wordfence malware-scan . -n eicar-test-file.php` or
`wordfence malware-scan . -x eicar-test-file.php`

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 171, in main
>     return cli.invoke()
>            ^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 164, in invoke
>     return subcommand.invoke()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/malwarescan/malwarescan.py", line 182, in invoke
>     metrics, timer = self.scanner.scan(
>                      ^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/scanning/scanner.py", line 796, in scan
>     file_locator_process.start()
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>                   ^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
>     return Popen(process_obj)
>            ^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'filter_filename.<locals>.filter'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/bin/wordfence", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 173, in main
>     return exception_handler.process_exception(exception)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 36, in process_exception
>     self.subcommand.terminate()
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/malwarescan/malwarescan.py", line 202, in terminate
>     self.scanner.terminate()
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/scanning/scanner.py", line 847, in terminate
>     active.terminate()
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 133, in terminate
>     self._popen.terminate()
>     ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'terminate'

**Comment by ewodrich** [comment]
Verified on Mac and Linux that the -n, -x, -N, -X commands are working as intended. Testing included testing singular or multiple files and file-patterns as applicable. Verified no errors in either environment and results reflected what was expected.
