### ISSUE TITLE
Scanning for sites with count-sites or vuln-scan on Mac fails when symlinks are present

### ISSUE THREAD

**Issue by ewodrich** [wordfence/wordfence-cli#211]
Testing "wordfence count-sites ." at parent directory containing 3 sites and a symlink to a site receives this error on Mac: 
`Error: Unable to scan directory at /Users/Esthe/Sites/wordpress`

The same error occurs when attempting wordfence vuln-scan

Debug Info: 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/wordpress/site.py", line 62, in _is_core_directory
>     if file.is_file():
>        ^^^^^^^^^^^^^^
> OSError: [Errno 62] Too many levels of symbolic links: '/Users/Esthe/Sites/wordpress/point-to-self'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/bin/wordfence", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 173, in main
>     return exception_handler.process_exception(exception)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 43, in process_exception
>     raise exception
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 171, in main
>     return cli.invoke()
>            ^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/cli.py", line 164, in invoke
>     return subcommand.invoke()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/countsites/countsites.py", line 26, in invoke
>     count += self.count_sites(path)
>              ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/cli/countsites/countsites.py", line 13, in count_sites
>     for core in locator.locate_core_paths():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/wordpress/site.py", line 144, in locate_core_paths
>     yield from self._search_for_core_directory()
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/wordpress/site.py", line 130, in _search_for_core_directory
>     if self._is_core_directory(directory):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wordfence/wordpress/site.py", line 75, in _is_core_directory
>     raise WordpressException(
> wordfence.wordpress.exceptions.WordpressException: Unable to scan directory at /Users/Esthe/Sites/wordpress

**Comment by ewodrich** [comment]
Error found when a symlink pointing to itself is in a scanned directory, such as `point-to-self -> point-to-self:` This particular symlink issue is on both Mac and Linux 

> wordfence count-sites . --debug
> Located WordPress site at /Users/Esthe/Sites/wpsite2
> Located WordPress site at /Users/Esthe/Sites/wpsite6.4.2/wordpress
> Unable to search child directory at /Users/Esthe/Sites/wordpress due to symlink error
> Located 2 WordPress site(s)
> 2

**Comment by ewodrich** [comment]
Tested various scenarios with `count-sites` and `vuln-scan` subcommands on Mac and Linux including:

- at base path with many sites
- simple singular site structures
- counting base + nested sites
- counting from nested site
- sites with and without a variety of symlinks
- a wp-config.php within a directory not containing a wp site (to verify it is not counted)
- comparing with count in: `find * -name "wp-config.php" | wc -l`
