### ISSUE TITLE
Error: need to escape, but no escapechar set

### ISSUE THREAD

**Issue by yusuf81** [wordfence/wordfence-cli#303]
When I scan my directory, it spit error. Then I try to scan last file in that list, it's success, with no error. 
Maybe there's a bug?, -d -v -L debug didn't show anything

(wordfence) root@sifiapve:/REDACTED/REDACTED/# wordfence -d -v -L DEBUG malware-scan /REDACTED/REDACTED/

             ▓▓▓
        ▓▓▓▓▓   ▓▓▓▓▓          _       __               __  ____
  ▓▓▓▓▓▓▓           ▓▓▓▓▓▓▓   | |     / /___  _________/ / / __/__  ____  ________
 ▓▓           ▓           ▓▓  | | /| / / __ \/ ___/ __  /_/ /_/ _ \/ __ \/ ___/ _ \
▓▓     ▓▓    ▓▓▓    ▓▓     ▓▓ | |/ |/ / /_/ / /  / /_/ /_  __/  __/ / / / /__/  __/
▓▓      ▓     ▓     ▓      ▓▓ |__/|__/\____/_/   \____/ /_/  \___/_/ /_/\___/\___/
▓▓    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    ▓▓                                       ____ _     ___
▓▓  ▓▓▓ ▓    ▓▓▓    ▓ ▓▓▓  ▓▓                                      / ___| |   |_ _|
▓▓▓▓▓   ▓    ▓▓▓    ▓   ▓▓▓▓▓                                     | |   | |    | |
 ▓▓     ▓   ▓▓ ▓▓   ▓     ▓▓                                      | |___| |___ | |
  ▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓                                        \____|_____|___|

Scanning path: /REDACTED/REDACTED/
File added to scan queue: /REDACTED/REDACTED/1650302011111531665635714.htm
Processing file: /REDACTED/REDACTED/1650302011111531665635714.htm
File added to scan queue: /REDACTED/REDACTED/205030100111130-DaftarHadir.php7
File added to scan queue: /REDACTED/REDACTED/1650302011111531665635713.htm
Processing file: /REDACTED/REDACTED/205030100111130-DaftarHadir.php7
Processing file: /REDACTED/REDACTED/1650302011111531665635713.htm
File added to scan queue: /REDACTED/REDACTED/1850301071110441637315225.htm
File added to scan queue: /REDACTED/REDACTED/1650302011111531665635728.htm
Processing file: /REDACTED/REDACTED/1850301071110441637315225.htm
Processing file: /REDACTED/REDACTED/1650302011111531665635728.htm
File added to scan queue: /REDACTED/REDACTED/205030100111130-NilaidariPerusahaan.php5
Processing file: /REDACTED/REDACTED/205030100111130-NilaidariPerusahaan.php5
File added to scan queue: /REDACTED/REDACTED/1950301071110011699953907.php7
Processing file: /REDACTED/REDACTED/1950301071110011699953907.php7
File added to scan queue: /REDACTED/REDACTED/205030100111130-KwitansiPembayaran.php
Processing file: /REDACTED/REDACTED/205030100111130-KwitansiPembayaran.php
File added to scan queue: /REDACTED/REDACTED/205030100111130-KartuBimbingan.php3
File added to scan queue: /REDACTED/REDACTED/1950301071110011699953980.phtml
File added to scan queue: /REDACTED/REDACTED/1750301011110091707844858.php
Processing file: /REDACTED/REDACTED/205030100111130-KartuBimbingan.php3
Error: need to escape, but no escapechar set

**Comment by akenion** [comment]
Due to #148, the options specified before `malware-scan` won't take effect. Can you try running it again with the options after to see if there's any additional debug output?

```
wordfence malware-scan -d -v -L DEBUG /REDACTED/REDACTED/
```

**Comment by yusuf81** [comment]
here the result:

```
             ▓▓▓
        ▓▓▓▓▓   ▓▓▓▓▓          _       __               __  ____
  ▓▓▓▓▓▓▓           ▓▓▓▓▓▓▓   | |     / /___  _________/ / / __/__  ____  ________
 ▓▓           ▓           ▓▓  | | /| / / __ \/ ___/ __  /_/ /_/ _ \/ __ \/ ___/ _ \
▓▓     ▓▓    ▓▓▓    ▓▓     ▓▓ | |/ |/ / /_/ / /  / /_/ /_  __/  __/ / / / /__/  __/
▓▓      ▓     ▓     ▓      ▓▓ |__/|__/\____/_/   \____/ /_/  \___/_/ /_/\___/\___/
▓▓    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓    ▓▓                                       ____ _     ___
▓▓  ▓▓▓ ▓    ▓▓▓    ▓ ▓▓▓  ▓▓                                      / ___| |   |_ _|
▓▓▓▓▓   ▓    ▓▓▓    ▓   ▓▓▓▓▓                                     | |   | |    | |
 ▓▓     ▓   ▓▓ ▓▓   ▓     ▓▓                                      | |___| |___ | |
  ▓▓▓▓▓▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓▓▓▓                                        \____|_____|___|

Filtered signature count: 6006
Using 8 worker(s)...
Worker 0 started, PID:984088
Worker 1 started, PID:984089
Worker 2 started, PID:984090
Worker 3 started, PID:984091
Worker 4 started, PID:984092
Scanning path: .
Awaiting results...
Worker 5 started, PID:984093
Worker 6 started, PID:984094
Worker 7 started, PID:984095
File added to scan queue: /REDACTED/REDACTED/REDACTED.htm
Processing file: /REDACTED/REDACTED/REDACTED.htm
File added to scan queue: /REDACTED/REDACTED/REDACTED-REDACTED.php7
File added to scan queue: /REDACTED/REDACTED/REDACTED.htm
Processing file: /REDACTED/REDACTED/REDACTED-REDACTED.php7
Processing file: /REDACTED/REDACTED/REDACTED.htm
File added to scan queue: /REDACTED/REDACTED/REDACTED.htm
File added to scan queue: /REDACTED/REDACTED/REDACTED.htm
Processing file: /REDACTED/REDACTED/REDACTED.htm
Processing file: /REDACTED/REDACTED/REDACTED.htm
File added to scan queue: /REDACTED/REDACTED/REDACTED.php5
Processing file: /REDACTED/REDACTED/REDACTED.php5
File added to scan queue: /REDACTED/REDACTED/REDACTED.php7
Processing file: /REDACTED/REDACTED/REDACTED.php7
File added to scan queue: /REDACTED/REDACTED/REDACTED.php
Processing file: /REDACTED/REDACTED/REDACTED.php
File added to scan queue: /REDACTED/REDACTED/REDACTED.php3
File added to scan queue: /REDACTED/REDACTED/REDACTED.phtml
File added to scan queue: /REDACTED/REDACTED/REDACTED.php
Processing file: /REDACTED/REDACTED/REDACTED.php3
Traceback (most recent call last):
  File "/root/wordfence/bin/wordfence", line 8, in <module>
    sys.exit(main())
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/cli.py", line 193, in main
    exit_code = invoke_cli()
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/cli.py", line 187, in invoke_cli
    return exception_handler.process_exception(exception)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/cli.py", line 43, in process_exception
    raise exception
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/cli.py", line 185, in invoke_cli
    return cli.invoke()
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/cli.py", line 178, in invoke
    return subcommand.invoke()
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/malwarescan/malwarescan.py", line 382, in invoke
    metrics, timer = self.scanner.scan(
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/scanning/scanner.py", line 1021, in scan
    worker_pool.await_results(result_processor)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/scanning/scanner.py", line 908, in await_results
    result_processor(result)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/malwarescan/reporting.py", line 139, in add_result
    self.write_records(records)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/reporting.py", line 446, in write_records
    self._write_record(record)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/reporting.py", line 441, in _write_record
    self._write_row(self._format_record(record), record)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/reporting.py", line 423, in _write_row
    writer.write_row(data)
  File "/root/wordfence/lib/python3.10/site-packages/wordfence/cli/reporting.py", line 100, in write_row
    self.writer.writerow(data)
_csv.Error: need to escape, but no escapechar set
```
